import { DB_PATH, path } from "../drizzle.config.ts";
import { drizzle } from "drizzle-orm/libsql"
import { createClient } from "@libsql/client";
import { migrate } from "drizzle-orm/libsql/migrator"


if (!path) {
    throw new Error("MEDICLOUD_DB_PATH is not defined!");
}
const client = createClient({ url: DB_PATH });


// relations here if needed


export const db = drizzle({ client });

/**
 * Initializes the MediCloud Agent database. 
 * Enables WAL mode and applies pending Drizzle migrations.
 */
export async function initDB() {
    // Enable SQLite Write-Ahead Logging.
    const result = await client.execute(
        "PRAGMA journal_mode = WAL;",
    );

    console.log("SQLite journal mode:", result.rows);

    // Apply pending migrations generated by Drizzle Kit.
    await migrate(db, { migrationsFolder: "./drizzle" })
}
